name: Sync Organization Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Add Upstream Organization Repository
        run: git remote add upstream https://github.com/N-NProject/frontend.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Changes into Forked Repository
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push Changes to Forked Repository
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_ACTIONS }}
